# -*- coding: utf-8 -*-
"""AI_Recruitment_Automation_Platform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfnaPczr0seLVYZjJyI4eM0iEkvqTUup
"""

# step 1

import gradio as gr
import requests, pandas as pd, re
from datetime import datetime
from typing import List

#KEYS
APP_ID  = "e95ec8af"
APP_KEY = "bd131c084783953905fd6a9a5e8ef627"

COUNTRIES = ["us","gb","ca","au","in"]

#role list
ROLE_CHOICES: List[str] = [
    "DevOps", "Site Reliability Engineer", "Platform Engineer", "Cloud Engineer",
    "Software Engineer", "Backend Engineer", "Frontend Engineer", "Full Stack Engineer",
    "Data Scientist", "Machine Learning Engineer", "AI Engineer", "MLOps Engineer",
    "Data Engineer", "Analytics Engineer", "Business Analyst", "Data Analyst",
    "NLP Engineer", "Computer Vision Engineer", "Deep Learning Engineer",
    "Security Engineer", "Cybersecurity", "Network Engineer", "Systems Engineer",
    "QA Engineer", "Automation Engineer", "Test Engineer",
    "Product Manager", "Technical Program Manager", "Project Manager",
    "Mobile Engineer", "iOS Engineer", "Android Engineer",
    "Embedded Engineer", "Firmware Engineer",
    "Solutions Architect", "Cloud Architect", "Data Architect",
    "Game Developer", "AR/VR Engineer", "Graphics Engineer",
    "Research Scientist", "Applied Scientist",
]

def _adzuna_request(country: str, what: str, where: str, days: int, max_results: int):
    """Fetch one page from Adzuna for a single country."""
    url = f"https://api.adzuna.com/v1/api/jobs/{country}/search/1"
    params = {
        "app_id": APP_ID,
        "app_key": APP_KEY,
        "results_per_page": max_results,
        "what": what,
        "where": where,
        "sort_by": "date",
        "max_days_old": int(days),
        "content-type": "application/json",
    }
    r = requests.get(url, params=params, timeout=20)
    r.raise_for_status()
    return r.json().get("results", [])

def _filter_client_side(rows, keyword: str, remote_only: bool):
    """Tighten results so typing 'DevOps' really shows DevOps, and filter remote if asked."""
    if not rows:
        return rows
    kw = keyword.strip().lower()
    out = []
    for it in rows:
        title = (it.get("title") or "")
        desc  = (it.get("description") or "")
        loc   = (((it.get("location") or {}) or {}).get("display_name") or "")
        # Keyword must appear in title OR description (case-insensitive)
        if kw and (kw not in title.lower() and kw not in desc.lower()):
            continue
        if remote_only:
            if ("remote" not in title.lower()
                and "remote" not in desc.lower()
                and "remote" not in loc.lower()):
                continue
        out.append(it)
    return out

def _normalize(rows, country_code: str):
    """Convert raw Adzuna rows to a clean table."""
    norm = []
    for j in rows:
        norm.append({
            "title": j.get("title",""),
            "company": ((j.get("company") or {}) or {}).get("display_name",""),
            "country": country_code.upper(),
            "location": ((j.get("location") or {}) or {}).get("display_name",""),
            "posted_at": j.get("created",""),
            "url": j.get("redirect_url",""),
            "description": j.get("description",""),
        })
    df = pd.DataFrame(norm)
    if not df.empty:
        df["posted_at"] = pd.to_datetime(df["posted_at"], errors="coerce")
        df = df.sort_values("posted_at", ascending=False).reset_index(drop=True)
    return df

def _render_html(df: pd.DataFrame) -> str:
    if df is None or df.empty:
        return "<div>No matching jobs.</div>"
    items = []
    for _, r in df.iterrows():
        t = (r["title"] or "(no title)")
        c = (r["company"] or "(no company)")
        u = (r["url"] or "#")
        l = (r["location"] or "")
        cc = (r["country"] or "")
        d = ""
        if pd.notna(r["posted_at"]):
            try:
                d = r["posted_at"].date().isoformat()
            except Exception:
                d = ""
        items.append(
            f'<li style="margin:6px 0">'
            f'<a href="{u}" target="_blank" rel="noopener noreferrer">{t}</a>'
            f' — {c} ({cc}{", " + l if l else ""}) · {d}'
            f"</li>"
        )
    return "<ol>" + "".join(items) + "</ol>"

def search_jobs_ui(role_or_keyword: str, country_pick: str, location_text: str,
                   remote_only: bool, days_recent: int, max_results: int):
    """Single-button search: tries your window; if empty, widens to 30 days."""
    if not APP_ID.strip() or not APP_KEY.strip():
        return "❌ Missing Adzuna APP_ID/APP_KEY.", "<div></div>", pd.DataFrame()

    #country list
    countries = COUNTRIES if country_pick == "All" else [country_pick]

    def run(days):
        all_rows = []
        for ctry in countries:
            try:
                raw = _adzuna_request(ctry, role_or_keyword, location_text, days, max_results)
            except Exception as e:
                continue

            tightened = _filter_client_side(raw, role_or_keyword, remote_only)
            df = _normalize(tightened, ctry)
            all_rows.append(df)
        if all_rows:
            df_all = pd.concat(all_rows, ignore_index=True)
            # keep top 'max_results' across all countries
            df_all = df_all.sort_values("posted_at", ascending=False).head(int(max_results)).reset_index(drop=True)
            return df_all
        return pd.DataFrame()

    # First pass: user-selected window
    df = run(days_recent)
    note = f"Showing jobs from last {days_recent} day(s)."
    # Fallback to 30 days if empty (or window < 30)
    if df.empty and days_recent < 30:
        df = run(30)
        note = f"No matches in last {days_recent} day(s). Showing up to 30-day results instead."

    if df.empty:
        return "No jobs found. Try another keyword, location, or increase days.", "<div>No matching jobs.</div>", df

    status = f"Found {len(df)} jobs. {note}"
    html = _render_html(df)
    # Trim columns for a clean table
    table = df[["title","company","country","location","posted_at","url"]].rename(columns={
        "title":"Title","company":"Company","country":"Country","location":"Location","posted_at":"Posted","url":"Link"
    })
    return status, html, table

#UI
gr.close_all()
with gr.Blocks(theme=gr.themes.Soft(primary_hue="blue")) as demo:
    gr.Markdown("## 🔎 Simple Job Search (Adzuna)")
    with gr.Row():
        role = gr.Dropdown(choices=ROLE_CHOICES, value="DevOps",
                           label="Role / Keyword", allow_custom_value=True)
        country = gr.Dropdown(choices=["All"] + COUNTRIES, value="All", label="Country")
    location = gr.Textbox(label="Location (optional)", placeholder="e.g., Remote, New York, London")
    with gr.Row():
        remote = gr.Checkbox(label="Remote only", value=False)
        days = gr.Slider(3, 30, value=14, step=1, label="Posted within (days)")
        maxr = gr.Slider(5, 50, value=25, step=1, label="Max results")

    go = gr.Button("🔍 Search Jobs", variant="primary")

    status = gr.Markdown()
    html_list = gr.HTML()
    table = gr.Dataframe(label="Results (click links in the HTML list above)", interactive=False)

    go.click(search_jobs_ui, [role, country, location, remote, days, maxr], [status, html_list, table])

print("✅ Ready.")
demo.launch(share=True, inline=False, inbrowser=True, debug=True)

#HARD RESET of conflicting deps
!pip -q uninstall -y websockets gradio gradio_client fastapi starlette pydantic pydantic-core \
    google-genai google-generativeai yfinance dataproc-spark-connect \
    langchain langchain-core albumentations >/dev/null 2>&1

# Pin websockets
!pip -q install websockets==14.1

# Gradio + HTTP stack
!pip -q install gradio==4.44.1 gradio_client==1.3.0 \
                fastapi==0.110.0 starlette==0.36.3 pydantic==2.6.4 pydantic-core==2.16.3

# other deps
!pip -q install "transformers>=4.42.0" "accelerate>=0.33.0" "torch>=2.2.0" \
                pdfminer.six python-docx openai google-generativeai

# quick version sanity print
import gradio, websockets, fastapi, starlette, pydantic, sys
print("gradio:", gradio.__version__)
print("websockets:", websockets.__version__)
print("fastapi:", fastapi.__version__)
print("starlette:", starlette.__version__)
print("pydantic:", pydantic.__version__)
print("python:", sys.version)

# Step 2
import os, re, json
import torch
import gradio as gr

#Resume parsing
from pdfminer.high_level import extract_text as pdf_extract_text
import docx

def read_file_text(file):
    if not file:
        return ""
    path = getattr(file, "name", None) or str(file)
    try:
        if path.lower().endswith(".txt"):
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                return f.read()
        elif path.lower().endswith(".pdf"):
            return pdf_extract_text(path)
        elif path.lower().endswith(".docx"):
            d = docx.Document(path)
            return "\n".join(p.text for p in d.paragraphs if p.text.strip())
        else:
            return ""
    except Exception as e:
        return f"Error reading file: {e}"

#LLMs using Google first else local fallback
SYSTEM = ("You are a precise, ATS-aware recruiter. "
          "Return clear, actionable advice; use short bullets and measurable changes.")

def llm_google(prompt: str) -> str:
    gkey = os.getenv("GOOGLE_API_KEY", "").strip()
    if not gkey:
        raise RuntimeError("NO_GOOGLE_KEY")
    import google.generativeai as genai
    genai.configure(api_key=gkey)
    model = genai.GenerativeModel(model_name="gemini-1.5-flash", system_instruction=SYSTEM)
    resp = model.generate_content(prompt)
    return (resp.text or "").strip()

# Local fallback (no key)
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
_local_tokenizer = None
_local_pipe = None

def llm_local(prompt: str) -> str:
    global _local_tokenizer, _local_pipe
    if _local_pipe is None:
        model_name = "Qwen/Qwen2.5-3B-Instruct"
        dtype = (
            torch.bfloat16 if (torch.cuda.is_available() and torch.cuda.is_bf16_supported())
            else torch.float16 if torch.cuda.is_available()
            else torch.float32
        )
        _local_tokenizer = AutoTokenizer.from_pretrained(model_name)
        _local_pipe = pipeline(
            "text-generation",
            model=AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=dtype, device_map="auto"),
            tokenizer=_local_tokenizer,
            do_sample=False,
            temperature=0.0,
        )
    if hasattr(_local_tokenizer, "apply_chat_template"):
        text_in = _local_tokenizer.apply_chat_template(
            [{"role":"system","content":SYSTEM},{"role":"user","content":prompt}],
            tokenize=False, add_generation_prompt=True
        )
    else:
        text_in = f"System: {SYSTEM}\nUser: {prompt}\nAssistant:"
    out = _local_pipe(text_in, max_new_tokens=700, pad_token_id=_local_tokenizer.eos_token_id)[0]["generated_text"]
    return out.split("Assistant:",1)[-1].strip()

def call_llm(prompt: str) -> str:
    try:
        return llm_google(prompt)
    except Exception:
        return llm_local(prompt)

#Matching helper
def contains_relaxed(text: str, term: str) -> bool:
    if not term or not text: return False
    t = term.strip().lower(); body = text.lower()
    if t in body: return True
    return re.search(r"(?:^|[^a-z0-9])"+re.escape(t)+r"(?:[^a-z0-9]|$)", body) is not None

def safe_json(s: str):
    try:
        return json.loads(s)
    except Exception:
        m = re.search(r"\{.*\}", s, re.DOTALL)
        if m:
            try: return json.loads(m.group(0))
            except Exception: pass
    return {}

PROMPT_JSON = """Read the job description and produce STRICT JSON with:
- must_have: list of core required skills/tech/experience
- tools: list of tools/tech/frameworks
- responsibilities: list of 5–8 short responsibilities
Do not include any keys other than these. Output ONLY JSON.

JOB DESCRIPTION:
\"\"\"{jd}\"\"\""""

PROMPT_SUGGEST = """You are tailoring a resume to this JD.

Return plain text with two sections ONLY:

[MatchPercent]
A number 0-100 estimating resume match to the JD.

[OverallChanges]
- 6–10 bullet points of concrete resume edits (rewrite bullets w/ metrics, reorder sections, highlight projects, quantify impact). Keep bullets short.

JOB DESCRIPTION:
\"\"\"{jd}\"\"\"

RESUME:
\"\"\"{resume}\"\"\""""

def analyze(jd_text, resume_file):
    jd_text = (jd_text or "").strip()
    if not jd_text:
        return "0.0", "Please paste a job description.", "—"

    resume_text = read_file_text(resume_file)
    if not resume_text or isinstance(resume_text, str) and resume_text.startswith("Error reading file:"):
        return "0.0", "Please upload a readable resume (PDF/DOCX/TXT).", "—"

    # Extract JD skills/tools/responsibilities
    jd_json_raw = call_llm(PROMPT_JSON.format(jd=jd_text[:12000]))
    jd_obj = safe_json(jd_json_raw)
    musts = [s.strip() for s in jd_obj.get("must_have", []) if str(s).strip()]
    tools = [s.strip() for s in jd_obj.get("tools", []) if str(s).strip()]
    resp  = [s.strip() for s in jd_obj.get("responsibilities", []) if str(s).strip()]

    # Coverage for simple score
    def cov(terms):
        if not terms: return 0.0
        hits = sum(1 for t in terms if contains_relaxed(resume_text, t))
        return hits / max(1, len(terms))
    score = (0.6*cov(musts) + 0.25*cov(tools) + 0.15*cov(resp)) * 100.0
    score_pct = round(float(score), 1)

    #Missing items to add in SKILLS section (top 10)
    missing_musts = [t for t in musts if not contains_relaxed(resume_text, t)]
    missing_tools = [t for t in tools if not contains_relaxed(resume_text, t)]
    skills_changes_list = (missing_musts + missing_tools)[:10]
    if skills_changes_list:
        skills_changes = "\n".join(f"• Add/Emphasize: {s}" for s in skills_changes_list)
    else:
        skills_changes = "• Skills section already covers the core requirements. Consider re-ordering to put the most relevant first."

    #Overall resume change suggestions (LLM)
    advice = call_llm(PROMPT_SUGGEST.format(jd=jd_text[:12000], resume=resume_text[:12000]))
    # Try to parse [MatchPercent]
    m = re.search(r"\[MatchPercent\]\s*([0-9]+(?:\.[0-9]+)?)", advice)
    if m:
        try:
            score_pct = float(m.group(1))
        except Exception:
            pass
    # Extract [OverallChanges]
    w = re.search(r"\[OverallChanges\](.*)$", advice, re.DOTALL | re.IGNORECASE)
    overall_changes = (w.group(1).strip() if w else advice.strip())
    # make sure bullets look clean
    if not overall_changes.startswith("-") and "•" not in overall_changes[:5]:
        overall_changes = "\n".join("- " + line.strip() for line in overall_changes.splitlines() if line.strip())

    return f"{score_pct}", skills_changes, overall_changes

#clean UI
CUSTOM_CSS = """
:root { --radius: 12px; }
.container { max-width: 980px !important; }
#jd_box textarea { min-height: 220px; }
.small-file .wrap { max-width: 300px; }
.card { background: #ffffff; border: 1px solid #e8ecf3; border-radius: 14px; padding: 12px; }
.kpi { font-size: 40px; font-weight: 800; line-height: 1; margin: 8px 0 2px; }
.kpi-sub { color:#6b7280; font-size: 12px; margin-bottom: 8px; }
"""

gr.close_all()
with gr.Blocks(theme=gr.themes.Soft(primary_hue="blue"), css=CUSTOM_CSS) as app:
    gr.Markdown("### Minimal JD → Resume Match")

    with gr.Row():
        with gr.Column(scale=6):
            jd = gr.Textbox(label="Job Description", placeholder="Paste the full JD here…", lines=12, elem_id="jd_box")
        with gr.Column(scale=4):
            resume = gr.File(label="Resume (PDF / DOCX / TXT)", file_types=[".pdf",".docx",".txt"],
                             type="filepath", elem_classes=["small-file"])
            analyze_btn = gr.Button("Analyze", variant="primary")

            with gr.Group(elem_classes=["card"]):
                kpi = gr.Markdown("**Match %**")
                match_pct = gr.Textbox(value="0.0", interactive=False, label=None)
                gr.Markdown('<div class="kpi-sub">Higher is better (aim >70%).</div>')

    with gr.Row():
        with gr.Column():
            with gr.Group(elem_classes=["card"]):
                gr.Markdown("**Skills — Add / Emphasize**")
                skills_changes = gr.Textbox(lines=10, interactive=False, label=None)
        with gr.Column():
            with gr.Group(elem_classes=["card"]):
                gr.Markdown("**Overall Resume Changes**")
                overall_changes = gr.Textbox(lines=10, interactive=False, label=None)

    analyze_btn.click(
        analyze,
        [jd, resume],
        [match_pct, skills_changes, overall_changes]
    )

# Use queue + open in new tab to avoid Colab "Failed to fetch"
app = app.queue(default_concurrency_limit=4)
app.launch(share=True, inline=False, inbrowser=True, debug=True)

#step 3
import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyBe9poJq-4MJbUc2T3JkMrWql18WuebivM"

# AI Inbox Hybrid
import os, re, json, datetime as dt
import pandas as pd
import gradio as gr


def _pick_engine(mode: str):
    if mode == "Local only":
        return "local"
    if mode == "API (OpenAI/Gemini)":
        return "google" if os.getenv("GOOGLE_API_KEY") else ("openai" if os.getenv("OPENAI_API_KEY") else "local")
    # Auto
    return "google" if os.getenv("GOOGLE_API_KEY") else ("openai" if os.getenv("OPENAI_API_KEY") else "local")

SYS_REPLY = (
    "You are a polite, concise recruiting coordinator. "
    "Write professional, short emails (max 6-8 sentences), plain text, American English. "
    "Keep subject context, propose next steps, friendly & efficient tone."
)


_LOCAL = {"tok": None, "pipe": None}

def _llm_api(prompt: str, engine: str) -> str:
    if engine == "google":
        import google.generativeai as genai
        genai.configure(api_key=os.environ["GOOGLE_API_KEY"])
        model = genai.GenerativeModel(model_name="gemini-1.5-flash", system_instruction=SYS_REPLY)
        resp = model.generate_content(prompt)
        return (resp.text or "").strip()
    if engine == "openai":
        from openai import OpenAI
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        r = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role":"system","content":SYS_REPLY},{"role":"user","content":prompt}],
            temperature=0.2,
        )
        return r.choices[0].message.content.strip()
    raise RuntimeError("API engine not available")

def _llm_local(prompt: str) -> str:
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
    if _LOCAL["pipe"] is None:
        name = "Qwen/Qwen2.5-3B-Instruct"
        dtype = torch.bfloat16 if (torch.cuda.is_available() and torch.cuda.is_bf16_supported()) else (torch.float16 if torch.cuda.is_available() else torch.float32)
        _LOCAL["tok"]  = AutoTokenizer.from_pretrained(name)
        model = AutoModelForCausalLM.from_pretrained(name, torch_dtype=dtype, device_map="auto")
        _LOCAL["pipe"] = pipeline("text-generation", model=model, tokenizer=_LOCAL["tok"], do_sample=False, temperature=0.0)
    if hasattr(_LOCAL["tok"], "apply_chat_template"):
        text_in = _LOCAL["tok"].apply_chat_template(
            [{"role":"system","content":SYS_REPLY},{"role":"user","content":prompt}],
            tokenize=False, add_generation_prompt=True
        )
    else:
        text_in = f"System: {SYS_REPLY}\nUser: {prompt}\nAssistant:"
    out = _LOCAL["pipe"](text_in, max_new_tokens=500, pad_token_id=_LOCAL["tok"].eos_token_id)[0]["generated_text"]
    return out.split("Assistant:",1)[-1].strip()

def LLM(prompt: str, mode: str) -> str:
    eng = _pick_engine(mode)
    try:
        if eng in ("google", "openai"):
            return _llm_api(prompt, eng)
        return _llm_local(prompt)
    except Exception:
        # graceful fallback chain
        if eng != "openai" and os.getenv("OPENAI_API_KEY"):
            try: return _llm_api(prompt, "openai")
            except Exception: pass
        return _llm_local(prompt)

# Heuristic labels (rules) + optional LLM assist
LABELS = ["Interested", "Not Interested", "Needs Follow-up", "Bounced/OOO"]
KW = {
    "interested": [r"\binterested\b", r"\bkeen\b", r"\blet'?s (talk|chat|connect|discuss)\b", r"\bschedule\b", r"\bbook (?:a )?call\b", r"\bavailable\b", r"\bproceed\b"],
    "no":         [r"\bnot interested\b", r"\bno thanks\b", r"\bpass\b", r"\bdeclin\w+\b", r"\bunsubscribe\b", r"\bremove me\b"],
    "follow":     [r"\bfollow[- ]?up\b", r"\bcircle back\b", r"\bnext week\b", r"\bmaybe\b", r"\bmore info\b", r"\bsend details\b", r"\bchecking in\b"],
    "ooo":        [r"\bout of office\b", r"\bauto[- ]?reply\b", r"\bon vacation\b", r"\bundeliverable\b", r"\bdelivery (?:has )?failed\b", r"\b550\b", r"\b5\.1\.1\b"],
}
def _hits(txt, pats): return sum(1 for p in pats if re.search(p, txt, re.I))

def classify_rules(subject: str, body: str):
    blob = f"{subject} {body}".lower()
    scores = {
        "Interested": _hits(blob, KW["interested"]),
        "Not Interested": _hits(blob, KW["no"]),
        "Needs Follow-up": _hits(blob, KW["follow"]),
        "Bounced/OOO": _hits(blob, KW["ooo"]),
    }
    label = max(scores, key=scores.get)
    tot = sum(scores.values())
    conf = 0.0 if tot == 0 else scores[label]/tot
    return label, round(conf,2)

def classify_llm(subject: str, body: str, mode: str):
    prompt = f"""Pick one label: {', '.join(LABELS)}.
Subject: {subject}
Body:
{body}

Return ONLY the label."""
    out = LLM(prompt, mode).strip().lower()
    for L in LABELS:
        if L.lower() in out:
            return L, 0.7
    return "Needs Follow-up", 0.5

# Time slots + reply
DEFAULT_CAL = "https://calendly.com/your-link/30min"

def propose_slots():
    now = dt.datetime.now()
    slots = []
    day = 0
    while len(slots) < 9 and day < 10:
        d = now + dt.timedelta(days=day+1)
        if d.weekday() < 5:
            for hr in (10, 14, 16):
                slots.append(d.replace(hour=hr, minute=0, second=0, microsecond=0).strftime("%a %b %d, %I:%M %p CT"))
        day += 1
    return slots[:9]

def draft_reply(row: dict, intent: str, extra: str, cal: str, mode: str):
    slots = "\n".join(f"- {s}" for s in propose_slots())
    name_guess = (row.get("from","").split("@")[0] or "there").split(".")[-1].title()
    subj = row.get("subject","").strip() or "the role"
    if intent == "Auto (by label)":
        intent = {"Interested":"Schedule","Not Interested":"Decline","Bounced/OOO":"Acknowledge OOO"}.get(row.get("label","Needs Follow-up"), "Follow-up")
    prompt = f"""
Write a short professional email reply.

Recipient: {row.get('from','')}
Recipient first-name guess: {name_guess}
Original Subject: {subj}
Detected Label: {row.get('label','Needs Follow-up')}
Selected Intent: {intent}
Calendar link: {cal or DEFAULT_CAL}
Suggested time slots (CT):
{slots}

If intent is Schedule: propose the times + calendar link.
If Follow-up: be polite, offer more info, optionally propose times.
If Answer FAQ: answer using the 'Extra info' below.
If Decline: thank and close.
If Acknowledge OOO: note you’ll follow up later.
If Request Info: list specifics you need.

Extra info:
{extra or '(none)'}

Constraints:
- 5–8 sentences max.
- Plain text only (no Markdown), friendly & efficient.
- Include a clear next step.
- End with a simple 'Best,' (no signatures or disclaimers).
"""
    return LLM(prompt, mode)

# I/O helpers
SAMPLE = [
    {"from":"alex@acme.com","subject":"Re: ML Engineer","body":"Yes, interested. Can we chat next week?","date":"2025-08-12"},
    {"from":"mailer-daemon@x.com","subject":"Delivery failed","body":"550 5.1.1 user unknown","date":"2025-08-12"},
    {"from":"sam@contoso.com","subject":"Not interested","body":"Thanks, not a fit right now.","date":"2025-08-11"},
    {"from":"lee@beta.io","subject":"Re: follow up","body":"Busy this week, circle back after Tuesday.","date":"2025-08-10"},
]
def parse_lines(text: str) -> pd.DataFrame:
    rows = []
    for line in (text or "").splitlines():
        parts = [p.strip() for p in line.split("|")]
        if len(parts) >= 3:
            rows.append({"from":parts[0], "subject":parts[1], "body":parts[2], "date":parts[3] if len(parts)>3 else ""})
    return pd.DataFrame(rows)

def load_messages(file, pasted):
    if file is not None:
        try:
            df = pd.read_csv(file.name)
        except Exception as e:
            return pd.DataFrame(SAMPLE), f"❌ CSV error: {e}"
    else:
        df = parse_lines(pasted)
        if df.empty: df = pd.DataFrame(SAMPLE)
    for c in ["from","subject","body","date"]:
        if c not in df.columns: df[c] = ""
    return df[["from","subject","body","date"]].copy(), "✅ Loaded."

def run_classify(df, use_llm, mode, filt):
    if df.empty: return df, 0, ""
    labels, confs = [], []
    for _, r in df.iterrows():
        L, C = classify_rules(r["subject"], r["body"])
        if C == 0 and use_llm:
            L, C = classify_llm(r["subject"], r["body"], mode)
        labels.append(L); confs.append(C)
    out = df.copy()
    out["label"], out["confidence"] = labels, confs
    if filt and filt != "All":
        out = out[out["label"] == filt]
    preview = ""
    if not out.empty:
        r = out.iloc[0].to_dict()
        preview = f"From: {r.get('from','')}\nSubject: {r.get('subject','')}\n\n{r.get('body','')}"
    return out, 0, preview

def show_row(df, idx):
    if df.empty: return ""
    idx = int(max(0, min(len(df)-1, int(idx))))
    r = df.iloc[idx].to_dict()
    return f"From: {r.get('from','')}\nSubject: {r.get('subject','')}\n\n{r.get('body','')}"

def do_reply(df, idx, intent, extra, cal, mode):
    if df.empty: return "No message selected."
    idx = int(max(0, min(len(df)-1, int(idx))))
    row = df.iloc[idx].to_dict()
    return draft_reply(row, intent, extra, cal, mode)

# UI
CSS = """
:root { --radius: 12px; }
.container { max-width: 1080px !important; }
.card { background:#fff; border:1px solid #e8ecf3; border-radius:14px; padding:12px; }
.small .wrap { max-width: 320px; }
th, td { font-size: 13px !important; }
"""

gr.close_all()
with gr.Blocks(theme=gr.themes.Soft(primary_hue="blue"), css=CSS) as app:
    gr.Markdown("### AI Inbox & Correspondence Manager — Hybrid (loads instantly)")

    with gr.Row():
        with gr.Column(scale=6):
            engine = gr.Dropdown(["Auto","API (OpenAI/Gemini)","Local only"], value="Auto", label="Engine")
            csv_in = gr.File(label="Upload CSV (from, subject, body, date)", file_types=[".csv"], elem_classes=["small"])
            paste = gr.Textbox(label="Quick paste (from | subject | body | date)", lines=3,
                               placeholder="alex@acme.com | Re: ML Engineer | yes, interested... | 2025-08-12")
            load_btn = gr.Button("Load", variant="secondary")
        with gr.Column(scale=6):
            use_llm = gr.Checkbox(label="Use LLM to assist labeling (when rules are unsure)", value=True)
            filt = gr.Dropdown(label="Filter", choices=["All"]+LABELS, value="All")
            class_btn = gr.Button("Auto-label", variant="primary")

    eng_note = gr.Markdown("")
    table = gr.Dataframe(label="Inbox", interactive=False, row_count=(0,"dynamic"))
    idx = gr.Number(label="Row #", value=0, precision=0)
    preview = gr.Textbox(label="Selected message", lines=10, interactive=False)

    with gr.Group(elem_classes=["card"]):
        gr.Markdown("**Smart Reply (LLM)**")
        intent = gr.Radio(["Auto (by label)","Schedule","Follow-up","Answer FAQ","Decline","Acknowledge OOO","Request Info"],
                          value="Auto (by label)", label=None)
        extra = gr.Textbox(label="FAQ / extra info (optional)", lines=4, placeholder="- Scope...\n- Process...\n- Timeline...")
        cal = gr.Textbox(label="Your calendar link", value=DEFAULT_CAL)
        gen_btn = gr.Button("Generate Reply", variant="primary")
        reply = gr.Textbox(label="Reply draft", lines=10)

    state = gr.State(pd.DataFrame(SAMPLE))

    def _load(file, txt, mode):
        df, _ = load_messages(file, txt)
        eng = _pick_engine(mode).upper()
        return df, df, f"**Active engine:** `{eng}`"

    load_btn.click(_load, [csv_in, paste, engine], [state, table, eng_note])
    class_btn.click(run_classify, [state, use_llm, engine, filt], [table, idx, preview])
    filt.change(run_classify, [state, use_llm, engine, filt], [table, idx, preview])
    idx.change(show_row, [table, idx], [preview])
    gen_btn.click(do_reply, [table, idx, intent, extra, cal, engine], [reply])

print("✅ Hybrid Inbox ready (no blocking at launch)")
app = app.queue(default_concurrency_limit=4)
app.launch(share=True, inline=False, inbrowser=True, debug=True)