# -*- coding: utf-8 -*-
"""Graphdb_NEO4j.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Ms7imK6S9aQmKA0zglo7mEylzAFGyh7
"""

# Install py2neo
!pip install py2neo
!pip install networkx matplotlib

from py2neo import Graph, Node, Relationship
import networkx as nx
import matplotlib.pyplot as plt

NEO4J_URI="neo4j+s://1d520d6f.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="DQVH_dLwEyVGfuBxgfBxXvc1ZurQE4jxLf7dMP7LxRw"

# Connect
graph = Graph(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

# Clear any existing data
graph.delete_all()

# Create nodes
alice = Node("Person", name="Alice")
bob = Node("Person", name="Bob")
llm = Node("Technology", name="LLM")

# Create relationships
graph.create(alice | bob | llm)
graph.create(Relationship(alice, "KNOWS", bob))
graph.create(Relationship(alice, "USES", llm))

print(" Graph data created successfully.")

query = """
MATCH (a:Person {name: 'Alice'})-[:KNOWS]->(b)
RETURN b.name AS name
"""

results = graph.run(query)
print("Alice knows:")
for row in results:
    print(row['name'])

G = nx.DiGraph()
G.add_edge("Alice", "Bob", label="KNOWS")
G.add_edge("Alice", "LLM", label="USES")

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_color='lightblue', node_size=2000, font_size=14)
edge_labels = nx.get_edge_attributes(G, 'label')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)
plt.title("Graph Database Visual (Alice's World)")
plt.show()